
//191220010 EMRAH CEYLAN OTOMATA ÖDEVİ

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author emrah
 */
public class mooreMakinesi extends javax.swing.JFrame {

    /**
     * Creates new form mooreMakinesi
     */
    public mooreMakinesi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tf_sonuc_input = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_sonuc_output = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_sonuc_durum = new javax.swing.JTextField();
        btn_pencere_kapat = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_sonuc1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_sonuc2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_sonuc3 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kumeler_panel = new javax.swing.JPanel();
        lb_kumeler1 = new javax.swing.JLabel();
        tf_kume1 = new javax.swing.JTextField();
        lb_kume2 = new javax.swing.JLabel();
        tf_kume2 = new javax.swing.JTextField();
        lb_kume3 = new javax.swing.JLabel();
        tf_kume3 = new javax.swing.JTextField();
        btn_ekle1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cb_durum = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_gecis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ftf_ciktilar = new javax.swing.JFormattedTextField();
        btn_ekle2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_input = new javax.swing.JTextField();
        btn_hesapla = new javax.swing.JButton();
        btn_temizle = new javax.swing.JButton();

        jDialog1.setBounds(new java.awt.Rectangle(0, 0, 700, 580));
        jDialog1.setResizable(false);
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialog1WindowOpened(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sonuçlar"));

        jLabel5.setText("Input");

        jLabel6.setText("Output");

        jLabel7.setText("Durumlar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_sonuc_input, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_sonuc_output, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tf_sonuc_durum)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_sonuc_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_sonuc_durum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_sonuc_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        btn_pencere_kapat.setText("Pencereyi Kapat");
        btn_pencere_kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pencere_kapatActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tablo"));

        ta_sonuc1.setColumns(20);
        ta_sonuc1.setRows(5);
        jScrollPane1.setViewportView(ta_sonuc1);

        ta_sonuc2.setColumns(20);
        ta_sonuc2.setRows(5);
        jScrollPane2.setViewportView(ta_sonuc2);

        ta_sonuc3.setColumns(20);
        ta_sonuc3.setRows(5);
        jScrollPane3.setViewportView(ta_sonuc3);

        jLabel8.setText("Eski Durum");

        jLabel9.setText("Geçişler");

        jLabel10.setText("Çıktı");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_pencere_kapat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_pencere_kapat)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("191220010_Emrah_Ceylan_Odev26");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        kumeler_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Kümeler"));

        lb_kumeler1.setText("Durumlar");

        tf_kume1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_kume1FocusGained(evt);
            }
        });

        lb_kume2.setText("Semboller Alfabesi");

        lb_kume3.setText("Olası Çıktı Sembolleri");

        btn_ekle1.setText("Ekle");
        btn_ekle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekle1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kumeler_panelLayout = new javax.swing.GroupLayout(kumeler_panel);
        kumeler_panel.setLayout(kumeler_panelLayout);
        kumeler_panelLayout.setHorizontalGroup(
            kumeler_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kumeler_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kumeler_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_kumeler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_kume1)
                    .addComponent(lb_kume2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_kume2)
                    .addComponent(lb_kume3, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(tf_kume3)
                    .addComponent(btn_ekle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kumeler_panelLayout.setVerticalGroup(
            kumeler_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kumeler_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_kumeler1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_kume1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_kume2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_kume2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_kume3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_kume3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ekle1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Girdi Ve Çıktılar"));

        cb_durum.setMaximumRowCount(20);

        jLabel1.setText("Durum");

        jLabel2.setText("Durumlar Arası Geçiş");

        tf_gecis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_gecisFocusGained(evt);
            }
        });

        jLabel3.setText("Çıktılar");

        ftf_ciktilar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btn_ekle2.setText("Ekle");
        btn_ekle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekle2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_durum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(tf_gecis)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ftf_ciktilar)
                    .addComponent(btn_ekle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_durum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_gecis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ftf_ciktilar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ekle2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        jLabel4.setText("Input");

        tf_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_inputFocusGained(evt);
            }
        });

        btn_hesapla.setText("Hesapla");
        btn_hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hesaplaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_input)
                    .addComponent(btn_hesapla, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_hesapla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_temizle.setText("Temizle");
        btn_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temizleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kumeler_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_temizle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kumeler_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btn_temizle)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /*Ekran ortalama fonksiyonu*/
    public static void ekranOrtalama(Window pencere) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - pencere.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - pencere.getHeight()) / 2);
        /*Ekranın x ve y uzunluklarından programın x ve y uzunları çıkartılıp 2'ye bölünür.
        Bu sayede orta nokta bulunmuş olur.*/
        pencere.setLocation(x, y);
    }
    
    
    int ilk_bilgilendirme = 0;
    int baslangic_bilgi_kumeler = 0;
    int gecisler_bilgi = 0;
    int input_bilgilendirme = 0;
    int durum_ekleme = 0;

    int ekle1 = 0;
    int ekle2 = 0;

    DefaultComboBoxModel myList;
    
    /*Global değişkenler, veri sayısı tam bilinmediğinden
    vektör olarak tanımlandı. Sonuçların başka yerlere yazılabilmesi
    için de global olarak tanımlandı.
    */

    Vector<String> durumlarKumesi = new Vector<String>();
    Vector<String> sembollerKumesi = new Vector<String>();
    Vector<String> ciktiKumesi = new Vector<String>();
    Vector<String> diziInput = new Vector<String>();

    Vector<String> durumVeGecisleri = new Vector<String>();

    Vector<String> sonucKumesi = new Vector<String>();
    Vector<String> sonucDurumlar = new Vector<String>();


    private void btn_ekle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekle1ActionPerformed
        
        /*Durumlar, geçişler alfabesi ve olası çıktıların eklendiği bölüm*/
        
        
        DefaultComboBoxModel myList = new DefaultComboBoxModel();

        String durumlar;
        String semboller;
        String ciktilar;

        durumlar = tf_kume1.getText();
        semboller = tf_kume2.getText();
        ciktilar = tf_kume3.getText();

        if (durumlar.equals("") || semboller.equals("") || ciktilar.equals("")) {
            JOptionPane.showMessageDialog(this, "Lütfen geçerli değerler giriniz.");
        } else {

            String[] diziDurumlar = durumlar.split(",");
            String[] diziSemboller = semboller.split(",");
            String[] diziCiktilar = ciktilar.split(",");

            durumlarKumesi.clear();
            sembollerKumesi.clear();
            ciktiKumesi.clear();

            for (int a = 0; a < diziDurumlar.length; a++) {
                durumlarKumesi.add(diziDurumlar[a]);
            }
            for (int a = 0; a < diziSemboller.length; a++) {
                sembollerKumesi.add(diziSemboller[a]);
            }
            for (int a = 0; a < diziCiktilar.length; a++) {
                ciktiKumesi.add(diziCiktilar[a]);
            }

            for (int a = 0; a < durumlarKumesi.size(); a++) {
                myList.addElement(durumlarKumesi.get(a));
            }
            cb_durum.setModel(myList);

            JOptionPane.showMessageDialog(this, "Durumlar, semboller, çıktılar eklendi.");

            btn_ekle2.setEnabled(true);
        }


    }//GEN-LAST:event_btn_ekle1ActionPerformed

    private void tf_gecisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_gecisFocusGained
        
        /*Geçişlerin nasıl yazılması gerektiği hakkında ufak bir bilgilendirme*/
        
        if (gecisler_bilgi == 0) {
            JOptionPane.showMessageDialog(this, "Durum seçildikten sonra, semboller alfabesinde \nyazdığınız sıraya göre geçişleri aralarında virgül olacak şekilde yazınız."
                    + "\nÖrnek\nSoldaki Semboller Alfabesi : a,b,c...\nDurumlar Arası Geçiş : q0,q3,q2..."
                    + "\n Seçili durumda a verildiğinde q0'a geçtiğini ifade eder.", "Bilgilendirme", JOptionPane.INFORMATION_MESSAGE);
            gecisler_bilgi = 1;
        }
    }//GEN-LAST:event_tf_gecisFocusGained

    
    /*Ekleme aşamasında uyuşmayı kontrol eden fonksiyon*/
    public boolean kontrol(String eklenecekDurum) {
        
        for (int a = 0; a < durumVeGecisleri.size(); a++) {
            String kontrol[] = durumVeGecisleri.get(a).split(",");

            if (eklenecekDurum.equals(kontrol[0])) {
                return false;
            }
        }
        return true;
    }
    
    //Yazılan geçişler durum kümesinde var mı kontrol edilir.
    public int kontrolDurumlarGecisleri(String gecisler){
        int kontrol = 0;
        String[] gecislerDizi = gecisler.split(",");
        for(int a = 0 ; a < gecislerDizi.length ; a++){
            for(int b = 0 ; b < durumlarKumesi.size() ; b++){
                if(gecislerDizi[a].equals(durumlarKumesi.get(b))){
                    kontrol = 1;
                    break;
                }else{
                    kontrol = 0;
                }
            }
            if(kontrol == 0){
                JOptionPane.showMessageDialog(this, gecislerDizi[a] + " durumlar kümesinde bulunamadı!", "Hata",JOptionPane.ERROR_MESSAGE);
                return 1;
            }
        }
        return 0;
    }


    private void btn_ekle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekle2ActionPerformed
        
        /*Seçili olan durumun, semboller alfabesindeki sıraya göre bir sonraki
        aşamada hangi durumda olacağı ve çıktı olarak ne vereceğinin eklendiği
        bölümdür.
        */
        
        
        /*Text Field içerisindeki bilgiler dizilere eklenir.*/
        String baslangicDurumu = cb_durum.getItemAt(cb_durum.getSelectedIndex());
        String durumlarArasiGecis = tf_gecis.getText();
        String durumunCiktisi = ftf_ciktilar.getText();
        
        if(durumlarArasiGecis.equals("") || ftf_ciktilar.equals("")){
            JOptionPane.showMessageDialog(this, "Lütfen geçerli değerler giriniz.");
        }else{
            if(kontrolDurumlarGecisleri(durumlarArasiGecis) == 0){
                String[] kontrolGecis = durumlarArasiGecis.split(",");
                if (kontrolGecis.length != sembollerKumesi.size()) {
                    /*Programın sol tarafında bulunan semboller alfabesi ile yazılan geçişler 
                    aynı uzunlukta olmalıdır. DFA gibi çalıştığından her geçişde ne olacağı 
                    bilgilendirilmelidir. Aşağıdaki kod satırı ise bu iki dizinin uzunluğunu
                    karşılaştırır.
                    */
                    JOptionPane.showMessageDialog(this, "Semboller alfabesi ile geçişleri ifade eden alfabe\n"
                            + "uzunluğu birbirinden farklı olamaz.", "Hata", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (durumVeGecisleri.size() <= 0) {
                        String tumIfade;
                        tumIfade = baslangicDurumu + "," + durumlarArasiGecis + "," + durumunCiktisi;
                        durumVeGecisleri.add(tumIfade);
                    } else {
                        if (kontrol(baslangicDurumu)) {
                            String tumIfade;
                            tumIfade = baslangicDurumu + "," + durumlarArasiGecis + "," + durumunCiktisi;
                            durumVeGecisleri.add(tumIfade);
                            JOptionPane.showMessageDialog(this, baslangicDurumu + " eklendi.");
                        } else {
                            JOptionPane.showMessageDialog(this, baslangicDurumu + " daha önce eklenmiş.");
                        }
                    }


                    if (durum_ekleme == 0) {
                        JOptionPane.showMessageDialog(this, "Tüm durumlar eklendiğinde hesapla butonu açılacaktır.");
                        durum_ekleme = 1;
                    }

                    if (durumVeGecisleri.size() == durumlarKumesi.size()) {
                        btn_hesapla.setEnabled(true);
                    }
                }

                tf_gecis.setText("");
                ftf_ciktilar.setText("");
            }  
        }

        


    }//GEN-LAST:event_btn_ekle2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        /*
        Test aşaması için içlerini hazır doldurma
        Verilen örnek doğrultusunda gerekli doldurma işlemleri gerçekleştirilir.
        Butonlar sırayla aktif edilerek sonuca hızlı ulaşım sağlanabilir.
        
        tf_kume1.setText("q0,q1,q2,q3");
        tf_kume2.setText("a,b");
        tf_kume3.setText("0,1");

        tf_gecis.setText("q3,q0");
        ftf_ciktilar.setText("1");

        durumVeGecisleri.add("q0,q1,q0,0");
        durumVeGecisleri.add("q1,q2,q0,0");
        durumVeGecisleri.add("q2,q2,q3,0");
        durumVeGecisleri.add("q3,q1,q0,1");

        tf_input.setText("aaababbaabb");
        */
        

        /*Kullanıcı tarafından etkileşimi yasaklamak için 
        bazı yerlerin değiştirilebilir özelliği kapatılır.*/
        btn_ekle2.setEnabled(false);
        btn_hesapla.setEnabled(false);
        ta_sonuc1.setEditable(false);
        ta_sonuc2.setEditable(false);
        ta_sonuc3.setEditable(false);
        
        
        //Ekran ortalama
        ekranOrtalama(this);
    }//GEN-LAST:event_formWindowOpened

    private void btn_hesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hesaplaActionPerformed
        

        if (durumVeGecisleri.size() != durumlarKumesi.size()) {

            String eklenenler = "";
            for (int a = 0; a < durumVeGecisleri.size(); a++) {
                String[] eklenenlerKumesi = durumVeGecisleri.get(a).split(",");
                eklenenler = eklenenler + " " + eklenenlerKumesi[0];
            }

            JOptionPane.showMessageDialog(this, "Tüm durumlar eklenmemiş.\nLütfen tüm durumların \ngeçişlerini ve çıktılarını ekleyiniz.\n"
                    + "Eklenen durumlar : " + eklenenler, "Hata", JOptionPane.ERROR_MESSAGE);

        } else {
            

            diziInput.clear();
            String input = tf_input.getText();
            for (int a = 0; a < input.length(); a++) {
                diziInput.add(input.substring(a, a + 1));
            }
            

            int baslangicDurumu = 0;
            String sonrakiDurum;
            String[] durumGecisKume;
            
            /*Sonraki durum, bize verilen durumlar kümesinin ilk elemanı 
            olarak belirlenir. Çünkü başlangıç state ilk sırada verildiği
            düşünülmektedir.*/
            sonrakiDurum = durumlarKumesi.get(0);

            String stringSonucDurumlar = "";
            String stringSonucCiktilar = "";
            

            /*Aşağıdaki kısımda diziler içerisinde bulunan durumlara göre 
            denk gelen yerler eşleştirilerek hangi durumda nereye geçileceği bulunur.
            Örneğin a input verildiğinde devam edilen durum için semboller alfabesinde 
            a'nın sırası bulunur. Bulunan sıraya göre, bulunan durumun geçişi durumVeGecisleri 
            dizisinde bir fazlasıyla eşleşmektedir. Çünkü ilk eleman durumu ifade etmektedir. Ara
            elemanlar ise geçişleri son eleman çıktıyı vermektedir. Sonuçlar bu sıraya göre atama yapılır.*/
            for (int a = 0; a < diziInput.size(); a++) {
                for (int b = 0; b < sembollerKumesi.size(); b++) {
                    if (diziInput.get(a).equals(sembollerKumesi.get(b))) {
                        for (int c = 0; c < durumVeGecisleri.size(); c++) {
                            durumGecisKume = durumVeGecisleri.get(c).split(",");
                            if (durumGecisKume[0].equals(sonrakiDurum)) {
                                sonucKumesi.add(durumGecisKume[durumGecisKume.length - 1]);
                                sonucDurumlar.add(sonrakiDurum);
                                sonrakiDurum = durumGecisKume[b + 1];
                                break;
                            }
                        }
                    }
                }
            }

            

            /*Son eleman yukarıda eksik kalır. Çünkü bir sonraki geçiş elemanına 
            bakılamadan dizi boyutuna ulaşılmış olur. Bu yüzden yukarıdaki aşamada bir kez daha tekrar
            edilir. Son elemanda bu sayede eklenmiş olur.*/
            String enSonInput = diziInput.lastElement();
            int sonInputIndeks = 0;
            for (int a = 0; a < sembollerKumesi.size(); a++) {
                if (enSonInput.equals(sembollerKumesi.get(a)));
                sonInputIndeks = a + 1;
            }
            for (int a = 0; a < durumVeGecisleri.size(); a++) {
                durumGecisKume = durumVeGecisleri.get(a).split(",");
                if (durumGecisKume[0].equals(sonrakiDurum)) {
                    sonrakiDurum = durumGecisKume[sonInputIndeks];
                    sonucKumesi.add(durumGecisKume[durumGecisKume.length - 1]);
                    sonucDurumlar.add(sonrakiDurum);
                }
            }
            
            
            //Sonuçlar string haline getirilir.
            for (int a = 0; a < sonucDurumlar.size(); a++) {

                stringSonucDurumlar = stringSonucDurumlar + " " + sonucDurumlar.get(a);
                stringSonucCiktilar = stringSonucCiktilar + " " + sonucKumesi.get(a);
                
            }
            

            tf_sonuc_input.setText(input);
            tf_sonuc_durum.setText(stringSonucDurumlar);
            tf_sonuc_output.setText(stringSonucCiktilar);
            
            //Tablo oluşturmak için aşağıdaki adımlar uygulanır.
            ta_sonuc1.setText("");
            ta_sonuc2.setText("");
            ta_sonuc3.setText("");

            for (int a = 0; a < durumVeGecisleri.size(); a++) {
                String[] splitDurumGecis = durumVeGecisleri.get(a).split(",");
                ta_sonuc1.append(splitDurumGecis[0]);
                for (int b = 1; b < splitDurumGecis.length - 1; b++) {
                    ta_sonuc2.append(splitDurumGecis[b] + "\t");
                }
                ta_sonuc3.append(splitDurumGecis[splitDurumGecis.length - 1]);
                ta_sonuc1.append("\n");
                ta_sonuc2.append("\n");
                ta_sonuc3.append("\n");
            }

            jDialog1.show(true);
            //Sonuçlar için diyalog penceresi açılır.
            
            sonucDurumlar.clear();
            sonucKumesi.clear();
            //Gerekli diziler temizlenir.
        }


    }//GEN-LAST:event_btn_hesaplaActionPerformed

    private void btn_pencere_kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pencere_kapatActionPerformed
        jDialog1.show(false);
    }//GEN-LAST:event_btn_pencere_kapatActionPerformed

    private void jDialog1WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowOpened
        
        ekranOrtalama(jDialog1);
        
        tf_sonuc_input.setEditable(false);
        tf_sonuc_output.setEditable(false);
        tf_sonuc_durum.setEditable(false);
    }//GEN-LAST:event_jDialog1WindowOpened

    private void btn_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temizleActionPerformed
        int soru = JOptionPane.showConfirmDialog(this, "Her şeyi temizlemek istediğinize emin misiniz?","Emin misiniz?",JOptionPane.OK_CANCEL_OPTION);
        if(soru == 0){
            try{
                //Tüm aşamalar tek tek silinir.
                tf_kume1.setText("");
                tf_kume2.setText("");
                tf_kume3.setText("");

                cb_durum.removeAllItems();
                tf_gecis.setText("");
                ftf_ciktilar.setText("");

                tf_input.setText("");

                tf_sonuc_input.setText("");
                tf_sonuc_output.setText("");
                tf_sonuc_durum.setText("");

                btn_ekle2.setEnabled(false);
                btn_hesapla.setEnabled(false);

                durumlarKumesi.clear();
                sembollerKumesi.clear();
                ciktiKumesi.clear();
                diziInput.clear();
                durumVeGecisleri.clear();
                sonucKumesi.clear();
                sonucDurumlar.clear();

                ekle1 = 0;
                ekle2 = 0;
                baslangic_bilgi_kumeler = 0;
                gecisler_bilgi = 0;
                durum_ekleme = 0;
                input_bilgilendirme = 0;
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Bir hata ile karşılaşıldı.");
            }
       
        }
    }//GEN-LAST:event_btn_temizleActionPerformed

    private void tf_kume1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_kume1FocusGained
        
        if(ilk_bilgilendirme == 0){
            JOptionPane.showMessageDialog(this, "Yazılacak olan alfabelerin sırası çok önemlidir.\n"
                + "Her yazılan sembol arasında virgül koymayı unutmayınız.\n"
                    + "Örnek semboller alfabesi = a,b,c","Bilgilendirme",JOptionPane.INFORMATION_MESSAGE);
            ilk_bilgilendirme = 1;
        }
        
    }//GEN-LAST:event_tf_kume1FocusGained

    private void tf_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_inputFocusGained
        
        if(input_bilgilendirme == 0){
        JOptionPane.showMessageDialog(this, "Input girilirken lütfen virgül olmadan giriniz..\n"
                + "Aralarda boşluk bırakılmadığından emin olunuz.","Bilgilendirme",JOptionPane.INFORMATION_MESSAGE);
        input_bilgilendirme = 1;
        }
    }//GEN-LAST:event_tf_inputFocusGained


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mooreMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mooreMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mooreMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mooreMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mooreMakinesi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ekle1;
    private javax.swing.JButton btn_ekle2;
    private javax.swing.JButton btn_hesapla;
    private javax.swing.JButton btn_pencere_kapat;
    private javax.swing.JButton btn_temizle;
    private javax.swing.JComboBox<String> cb_durum;
    private javax.swing.JFormattedTextField ftf_ciktilar;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel kumeler_panel;
    private javax.swing.JLabel lb_kume2;
    private javax.swing.JLabel lb_kume3;
    private javax.swing.JLabel lb_kumeler1;
    private javax.swing.JTextArea ta_sonuc1;
    private javax.swing.JTextArea ta_sonuc2;
    private javax.swing.JTextArea ta_sonuc3;
    private javax.swing.JTextField tf_gecis;
    private javax.swing.JTextField tf_input;
    private javax.swing.JTextField tf_kume1;
    private javax.swing.JTextField tf_kume2;
    private javax.swing.JTextField tf_kume3;
    private javax.swing.JTextField tf_sonuc_durum;
    private javax.swing.JTextField tf_sonuc_input;
    private javax.swing.JTextField tf_sonuc_output;
    // End of variables declaration//GEN-END:variables
}
